### ISSUE TITLE
Book building failed

### ISSUE THREAD

**Issue by githubliuqi** [JoelCourtney/mdbook-kroki-preprocessor#33] opened 2024-01-23 12:24 UTC
2024-01-23 20:21:19 [INFO] (mdbook::book): Book building has started
HTTP status client error (400 Bad Request) for url (https://kroki.io/)

2024-01-23 20:21:21 [ERROR] (mdbook::utils): Error: The "kroki-preprocessor" preprocessor exited unsuccessfully with exit status: 1 status

**Comment by JoelCourtney** [comment] 2024-01-25 00:40
Unable to reproduce. Can you give me more information? What diagram are you trying to render?

**Comment by JoelCourtney** [comment] 2024-02-15 20:25
Closing. If you can provide more details I'll reopen. Thanks

**Closed as completed by JoelCourtney** 2024-02-15 20:25 UTC
Labels: bug

**Comment by bartvanderwal** [comment] 2024-09-22 06:12
I have the same issue. Getting an error `HTTP status client error (400 Bad Request) for url (https://kroki.io/)` on running `mdbook build` (or `mdbook serve` 😉 ).

```console
mdbook-kroki-test % mdbook serve
2024-09-22 07:13:54 [INFO] (mdbook::book): Book building has started
HTTP status client error (400 Bad Request) for url (https://kroki.io/)

2024-09-22 07:13:54 [ERROR] (mdbook::utils): Error: The "kroki-preprocessor" preprocessor exited unsuccessfully with exit status: 1 status
bartvanderwal@MBP-van-Bart mdbook-kroki-test % 
```

My `mdbook --version`: `mdbook v0.4.40`
The mdbook-kroki-preprocessor is v0.2.0 I believe, bit it's NOT specified it only mentions `kroki-preprocessor` 😏 

```console
mdbook-kroki-preprocessor --version
kroki-preprocessor
```

**Comment by bartvanderwal** [comment] 2024-09-22 06:13
For reproduction I have created a minimal GitHub repo:

https://github.com/bartvanderwal/mdbook-kroki-test

**Comment by bartvanderwal** [comment] 2024-09-22 13:10
Note that - as mentioned in that issue that on running mdbook build.

```markdown
# Les 2 - ORM (EF core)

<kroki type="erd">
  [Student]
  *Naam
  +Student nummer
</kroki>
```

The error goes away, and the book compiles correct when I remove a space in the student number field and change it to `student_number` for instance.

```markdown
# Les 2 - ORM (EF core)

<kroki type="erd">
  [Student]
  *Naam
  +Student_nummer

</kroki>
```

Or by surrounding it with quotes I can even keep the space:

```mdbook
  +"Student nummer"
```

The actual issue is of course that it would be much clearer on an input format issue that kroki-preprocessor would also give the inner exception of the `400` (client side error) exception to the user to give some hints, where to look. The way that the online kroki processor/sandbox does:

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/30e48849-c82a-4e3e-8bb2-ece060438d21">


```
"" (line 3, column 12): unexpected 'n' expecting attribute (exit code 1)
```

**Comment by bartvanderwal** [comment] 2024-09-22 17:24
@JoelCourtney Could you reopen, based on this reproduction path?
